version: '3.9'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379'
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=orders
    ports:
      - '27017'
    volumes:
      - mongodb_data_container:/data/db
  backend:
    build:
      context: .
    container_name: backend
    environment:
      - NODE_ENV=local
      - PORT=3000
      - VERSION=v1
      - MONGO_HOST=mongodb://mongo:27017/orders
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
      - /node_modules
volumes:
  mongodb_data_container: