version: '3.9'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379'
  mongodb_container:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      - MONGO_INITDB_DATABASE=orders
    ports:
      - '27017'
    volumes:
      - mongodb_data_container:/data/db
  backend:
    build:
      context: .
    container_name: backend
    ports:
      - '3000:3000'
    depends_on:
      - mongodb_container
      - redis
    volumes:
      - .:/app
      - /node_modules
volumes:
  mongodb_data_container: